# Generated by Django 5.2.8 on 2025-11-26 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Playbook name (3-100 characters)", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description (10-500 characters)",
                        max_length=500,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("design", "Design"),
                            ("development", "Development"),
                            ("research", "Research"),
                            ("management", "Management"),
                            ("product", "Product"),
                            ("other", "Other"),
                        ],
                        help_text="Playbook category",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tag strings"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private (only me)"),
                            ("family", "Family"),
                            ("local_only", "Local only (not uploaded to Homebase)"),
                        ],
                        default="private",
                        help_text="Who can see this playbook",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Playbook status",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version (auto-set on creation)",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this playbook was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this playbook was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this playbook",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by", "status"],
                        name="methodology_created_91075a_idx",
                    ),
                    models.Index(
                        fields=["category"], name="methodology_categor_c1963b_idx"
                    ),
                    models.Index(
                        fields=["visibility"], name="methodology_visibil_a5f9ac_idx"
                    ),
                ],
                "unique_together": {("created_by", "name")},
            },
        ),
    ]
