# Generated by Django 5.2.8 on 2025-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="workflow",
            name="order",
            field=models.IntegerField(
                default=1, help_text="Execution order within playbook"
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name="workflow",
            constraint=models.UniqueConstraint(
                fields=("playbook", "name"), name="unique_workflow_per_playbook"
            ),
        ),
    ]
