# Generated by Django 5.2.8 on 2025-11-25 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("playbook_created", "Playbook Created"),
                            ("playbook_updated", "Playbook Updated"),
                            ("playbook_deleted", "Playbook Deleted"),
                            ("playbook_viewed", "Playbook Viewed"),
                            ("dashboard_viewed", "Dashboard Viewed"),
                            ("workflow_created", "Workflow Created"),
                            ("workflow_updated", "Workflow Updated"),
                            ("workflow_deleted", "Workflow Deleted"),
                            ("activity_created", "Activity Created"),
                            ("activity_updated", "Activity Updated"),
                            ("activity_deleted", "Activity Deleted"),
                            ("pip_created", "PIP Created"),
                            ("pip_approved", "PIP Approved"),
                            ("pip_rejected", "PIP Rejected"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what happened",
                        max_length=500,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this action occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data about the action",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related playbook if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="methodology.playbook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who performed this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="methodology_user_id_b5502f_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="methodology_action__527068_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="methodology_timesta_b8e6d0_idx"
                    ),
                ],
            },
        ),
    ]
