# Generated by Django 5.2.8 on 2025-11-26 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Workflow name (e.g., 'Discovery Phase', 'User Research')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this workflow accomplishes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status of this workflow",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of workflows within playbook"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this workflow",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        help_text="Playbook this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="methodology.playbook",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Workflows",
                "ordering": ["order", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("playbook", "name"),
                        name="unique_workflow_name_per_playbook",
                    )
                ],
            },
        ),
    ]
