# Generated by Django 5.2.8 on 2025-11-30 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0002_alter_workflow_options_workflow_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="3-letter abbreviation generated from workflow name (e.g., 'Design Features' -> 'DFT')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("released", "Released"),
                    ("disabled", "Disabled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="version",
            field=models.DecimalField(
                decimal_places=1,
                default=0.1,
                help_text="Draft: 0.1, 0.2, etc. Released: 1.0, 2.0, etc.",
                max_digits=5,
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Activity name - must be unique within workflow",
                        max_length=200,
                    ),
                ),
                (
                    "guidance",
                    models.TextField(
                        help_text="Rich Markdown guidance with instructions, examples, images, and diagrams"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Execution order within workflow"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        help_text="Optional phase grouping (e.g., 'Planning', 'Execution')",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous activity that must complete first",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="methodology.activity",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Next activity that depends on this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessors",
                        to="methodology.activity",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Parent workflow containing this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="methodology.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["workflow", "order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "name"), name="unique_activity_per_workflow"
                    )
                ],
            },
        ),
    ]
