# Generated by Django 5.2.8 on 2025-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0002_activity"),
        ("methodology", "0002_alter_workflow_options_workflow_order_and_more"),
    ]

    operations = []
