# Generated by Django 5.2.8 on 2025-11-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0002_alter_workflow_options_workflow_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Activity name - must be unique within workflow",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the activity"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Execution order within workflow"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        help_text="Optional phase grouping (e.g., 'Planning', 'Execution')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="not_started",
                        help_text="Current status of the activity",
                        max_length=20,
                    ),
                ),
                (
                    "has_dependencies",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this activity has prerequisite dependencies",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Parent workflow containing this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="methodology.workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["workflow", "order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "name"), name="unique_activity_per_workflow"
                    )
                ],
            },
        ),
    ]
