# Generated by Django 5.2.8 on 2025-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0003_workflow_abbreviation_alter_playbook_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="last_accessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when activity was last accessed/viewed (for Recent Activity tracking)",
                null=True,
            ),
        ),
    ]
