# Generated by Django 5.2.8 on 2025-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0003_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="status",
        ),
    ]
