# Generated by Django 6.0 on 2025-12-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0004_add_last_accessed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Artifact name - must be unique within activity",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the artifact"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Document", "Document"),
                            ("Template", "Template"),
                            ("Code", "Code"),
                            ("Diagram", "Diagram"),
                            ("Data", "Data"),
                            ("Other", "Other"),
                        ],
                        default="Document",
                        help_text="Type of artifact",
                        max_length=50,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, help_text="Whether this artifact is required"
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional template file attachment",
                        null=True,
                        upload_to="artifacts/templates/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Activity that produces this artifact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="methodology.activity",
                    ),
                ),
                (
                    "playbook",
                    models.ForeignKey(
                        help_text="Parent playbook for breadcrumb navigation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="methodology.playbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact",
                "verbose_name_plural": "Artifacts",
                "ordering": ["activity", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArtifactInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Activity that consumes this artifact",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_inputs",
                        to="methodology.activity",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        help_text="Artifact being consumed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consuming_activities",
                        to="methodology.artifact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Input",
                "verbose_name_plural": "Artifact Inputs",
                "ordering": ["activity", "artifact"],
            },
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                fields=("activity", "name"), name="unique_artifact_per_activity"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifactinput",
            constraint=models.UniqueConstraint(
                fields=("activity", "artifact"),
                name="unique_artifact_input_per_activity",
            ),
        ),
    ]
