# Generated by Django 5.2.8 on 2025-11-29 23:04

from django.db import migrations, models
import re


def generate_abbreviations_for_existing_workflows(apps, schema_editor):
    """Generate abbreviations for existing workflows."""
    Workflow = apps.get_model("methodology", "Workflow")
    
    for workflow in Workflow.objects.all():
        # Use same logic as model method
        name = workflow.name.strip()
        words = re.findall(r'\w+', name)
        
        if not words:
            workflow.abbreviation = 'WKF'
        elif len(words) == 1:
            word = words[0].upper()
            if len(word) >= 3:
                workflow.abbreviation = f"{word[0]}{word[len(word)//2]}{word[-1]}"
            elif len(word) == 2:
                workflow.abbreviation = f"{word[0]}{word[1]}X"
            else:
                workflow.abbreviation = f"{word[0]}WF"
        else:
            first_word = words[0].upper()
            last_word = words[-1].upper()
            letter1 = first_word[0]
            letter2 = last_word[0]
            
            if len(last_word) >= 2:
                letter3 = last_word[-1]
            elif len(first_word) >= 2:
                letter3 = first_word[1]
            else:
                letter3 = 'X'
            
            workflow.abbreviation = f"{letter1}{letter2}{letter3}"
        
        workflow.save()


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0005_rename_description_to_guidance"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="3-letter abbreviation generated from workflow name (e.g., 'Design Features' -> 'DFT')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="guidance",
            field=models.TextField(
                help_text="Rich Markdown guidance with instructions, examples, images, and diagrams"
            ),
        ),
        migrations.RunPython(
            generate_abbreviations_for_existing_workflows,
            reverse_code=migrations.RunPython.noop
        ),
    ]
