# Generated by Django 5.2.8 on 2025-11-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0006_add_workflow_abbreviation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="has_dependencies",
        ),
        migrations.AddField(
            model_name="activity",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                help_text="Previous activity that must complete first",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="successors",
                to="methodology.activity",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                help_text="Next activity that depends on this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessors",
                to="methodology.activity",
            ),
        ),
    ]
