# Generated by Django 5.2.8 on 2025-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("methodology", "0007_add_activity_dependencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("released", "Released"),
                    ("disabled", "Disabled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playbook",
            name="version",
            field=models.DecimalField(
                decimal_places=1,
                default=0.1,
                help_text="Draft: 0.1, 0.2, etc. Released: 1.0, 2.0, etc.",
                max_digits=5,
            ),
        ),
    ]
